apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: demo
  namespace: default
spec:
  selector:
    matchLabels:
      run: demo
  template:
    metadata:
      labels:
        run: demo
    spec:
      containers:
      - image: gcr.io/ninth-bonito-276003/everistest:tag1
        imagePullPolicy: IfNotPresent
        name: demo
        ports:
        - containerPort: 80
          protocol: TCP
